Ashvini/FirstWebApplication/src/main/java/com/web/model/TD.java
package com.web.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;


@Entity
@Table(name = "todos")
public class TD {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    private String userName;

    @Size(min = 10, message = "Enter at least 10 Characters...")
    private String description;

    private Date targetDate;
    
    private Date taskAssignedDate;
    private Date taskUpdatedDate;
   

	private boolean isDone;
    

    public TD() {
        super();
    }

    public TD(Long id,String userName, String description, Date taskAssignedDate, Date taskUpdatedDate, Date targetDate, boolean isDone) {
        super();
        this.id = id;
        this.userName = userName;
        this.description = description;
        this.taskAssignedDate = taskAssignedDate;
        this.taskUpdatedDate =taskUpdatedDate;
        this.targetDate = targetDate;
        this.isDone = isDone;
    }
    


    public Date getTaskAssignedDate() {
		return taskAssignedDate;
	}

	public void setTaskAssignedDate(Date taskAssignedDate) {
		this.taskAssignedDate = taskAssignedDate;
	}

	public Date getTaskUpdatedDate() {
		return taskUpdatedDate;
	}

	public void setTaskUpdatedDate(Date taskUpdatedDate) {
		this.taskUpdatedDate = taskUpdatedDate;
	}

	public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getTargetDate() {
        return targetDate;
    }

    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }
    
    public boolean isDone() {
		return isDone;
	}

	public void setDone(boolean isDone) {
		this.isDone = isDone;
	}
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        TD other = (TD) obj;
        if (id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return String.format(
                "TD [id=%s, userName=%s, description=%s, taskAssignedDate = %s,taskUpdatedDate = %s, targetDate=%s, isDone=%s]", id,
                userName, description,taskAssignedDate,taskUpdatedDate, targetDate, isDone);
    }

}

Ashvini/FirstWebApplication/src/main/java/com/web/controller/WelcomeController.java
package com.web.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.SessionAttributes;

import com.web.model.TD;
import com.web.service.TDService;

@Controller
//@SessionAttributes("name")
public class WelcomeController 
{
	
	 @RequestMapping(value = "/", method = RequestMethod.GET)
	    public String showWelcomePage(ModelMap model) {
	        model.put("name", getLoggedinUserName());
	        return "Welcome";
	    }
	 
	 
	 private String getLoggedinUserName() {
	        Object principal = SecurityContextHolder.getContext()
	            .getAuthentication().getPrincipal();

	        if (principal instanceof UserDetails) {
	            return ((UserDetails) principal).getUsername();
	        }

	        return principal.toString();
	    }
}



/*@RequestMapping(value="/login", method = RequestMethod.GET)
public String showLoginPage(ModelMap model){
	return "login";
}

@RequestMapping(value="/login", method = RequestMethod.POST)
public String showWelcomePage(ModelMap model, @RequestParam String name){
	model.put("name", name);
	return "Welcome";
	}*/

// @RequestMapping(value="/ShowT", method = RequestMethod.GET)	
// public String Show()
//{
	//return  "ShowT";
//}

Ashvini/FirstWebApplication/src/main/webapp/WEB-INF/jsp/ShowT.jsp
<html>



<head>


<title>My First Html Form</title>
</head>

<body>
 <H1>Welcome  ${name} <a href ="/Show">click here</a> to manage your todos.</H1>
 ${todos}
 
</body>


</html>

Ashvini/FirstWebApplication/src/main/webapp/WEB-INF/jsp/Welcome.jsp
<html>



<head>


<title>My First Html Form</title>
</head>

<body>
 <H1>Welcome  ${name} <a href ="/list-todos">click here</a> to manage your todos.</H1>
 ${todos}
 
</body>


</html>

Ashvini/FirstWebApplication/src/main/webapp/WEB-INF/jsp/list-todos.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>


<html>

<head>
<title>Todo's for ${name}</title>
<link href="webjars/bootstrap/3.3.6/css/bootstrap.min.css"
	rel="stylesheet">
</head>

<body>

<nav role="navigation" class="navbar navbar-default">

	<div class="navbar-collapse">
		<ul class="nav navbar-nav">
			<li class="active"><a href="/">Home</a></li>
	<li><a href="/list-todos" > Todos </a> </li>
		</ul>
	</div>
</nav>
	<div class="container">
		<table class="table table-striped">
			<caption>
			<H1>Your todos are </H1></caption>
			<thead>
				<tr>
					<th>Id</th>
					<th>User</th>
					<th>Description</th>
					<th>AssignedDate</th>
					<th>UpdatedDate</th>
					<th>Target Date</th>
					<th>Is it Done?</th>
				<<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${todos}" var="todo">
					<tr>
						<td>${todo.id}</td>
						<td>${todo.userName}</td>
						<td>${todo.description}</td>
						<td><fmt:formatDate value="${todo.taskAssignedDate}" pattern="dd/MM/yyyy"/></td>
						<td><fmt:formatDate value="${todo.taskUpdatedDate}" pattern="dd/MM/yyyy"/></td>
						<td><fmt:formatDate value="${todo.targetDate}" pattern="dd/MM/yyyy"/></td>
						<td>${todo.done}</td>
						<td><a type="button" class="btn btn-success"
							href="/update-todo?id=${todo.id}">Update</a></td>
						<td><a type="button" class="btn btn-warning"
							href="/delete-todo?id=${todo.id}">Delete</a></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<div> <a class="button" href="/add-todo">Add a Todo</a></div>
		<script src="webjars/jquery/1.9.1/jquery.min.js"></script>
	    <script src="webjars/bootstrap/3.3.6/js/bootstrap.min.js"></script>
		
	</div>
</body>

</html>

Ashvini/FirstWebApplication/src/main/webapp/WEB-INF/jsp/login.jsp
<!DOCTYPE html>
<html>
<head>


<title>My First Html Form</title>
</head>
<body>

Employee Login
<form method="post"/>
	Name:<input type ="text" name ="name"/>
	Password:<input type ="text" name ="password"/>
	<input type ="submit"/>
	<font color ="red"> ${errorMessage} </font>
	
	
</form>

</body>


</html>

Ashvini/FirstWebApplication/src/main/webapp/WEB-INF/jsp/todo.jsp
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>  
<html>
<head>
<title>First Web Application</title>
<link href="webjars/bootstrap/3.3.6/css/bootstrap.min.css"
	rel="stylesheet">

</head>

<body>
	<div class="container">

	<form:form method="post" modelAttribute="todo">
      <form:hidden path="id" />
      
     <!--  <fieldset class="form-group">
				<form:label path="userName">User</form:label> 
				<form:input path="userName" type="text"
					class="form-control" required="required"/>
					<form:errors path="userName" cssClass="text-warning"/>
					
			</fieldset> -->
      <fieldset class="form-group">
       <form:label path="description">Description</form:label>
       <form:input path="description" type="text" class="form-control"
        required="required" />
       <form:errors path="description" cssClass="text-warning" />
      </fieldset>
			<fieldset class="form-group">
				<form:label path="taskAssignedDate">AssignedDate</form:label> 
				<form:input path="taskAssignedDate" type="text"
					class="form-control" required="required"/>
					<form:errors path="taskAssignedDate" cssClass="text-warning"/>
					
			</fieldset>
			<fieldset class="form-group">
				<form:label path="taskUpdatedDate">UpdatedDate</form:label> 
				<form:input path="taskUpdatedDate" type="text"
					class="form-control" required="required"/>
					<form:errors path="taskUpdatedDate" cssClass="text-warning"/>
					
			</fieldset>
			<fieldset class="form-group">
				<form:label path="targetDate">TargetDate</form:label> 
				<form:input path="targetDate" type="text"
					class="form-control" required="required"/>
					<form:errors path="targetDate" cssClass="text-warning"/>
					
			</fieldset>
			
			<button type="submit" class="btn btn-success">Add</button>
		</form:form>
	</div>

	<script src="webjars/jquery/1.9.1/jquery.min.js"></script>
	<script src="webjars/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="webjars/bootstrap-datepicker/1.0.1/js/bootstrap-datepicker.js"></script>


	<script>
    $(function () {
        $("#targetDate").datepicker();
    });
</script>
<script>
    $(function () {
        $("#taskAssignedDate").datepicker();
    });
</script>
<script>
    $(function () {
        $("#taskUpdatedDate").datepicker();
    });
</script>
</body>

</html>